/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_interface.view;

import javax.swing.JOptionPane;

/**
 *
 * @author samueldouglasdossantos
 */
public class CadastroPJ_sdi extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPJ_sdi
     */
    public CadastroPJ_sdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JButton btn_salvar_CadastroPF = new javax.swing.JButton();
        javax.swing.JButton btn_enviar_CadastroPF = new javax.swing.JButton();
        javax.swing.JButton btn_excluir = new javax.swing.JButton();
        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.ButtonGroup buttonGroup2 = new javax.swing.ButtonGroup();
        telaCadastroPJ = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        CampNomeEmpreCadasPJ = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JFormattedTextField campCNPJCadasPJ = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        campSenhaCadasPJ = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JFormattedTextField campCEPCadasPJ = new javax.swing.JFormattedTextField();
        javax.swing.JTextField campRuaCadasPJ = new javax.swing.JTextField();
        javax.swing.JTextField campBairroCadasPJ = new javax.swing.JTextField();
        javax.swing.JTextField campNumeRuaCadasPJ = new javax.swing.JTextField();
        javax.swing.JTextField campUFCadasPJ = new javax.swing.JTextField();
        javax.swing.JButton btnVoltarCadasPJ = new javax.swing.JButton();
        javax.swing.JButton bntSalvarCadasPJ = new javax.swing.JButton();
        javax.swing.JButton bntEntrarCadasPJ = new javax.swing.JButton();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu botaoMenuUsuario = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuCadastreSeUsuarioPF = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuEsqueUsuarioSenhaPF = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoUsuarioMenuSairPF = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuCadastreSePJ = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuLoginPJ = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuCadrasteSePJ = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuContato = new javax.swing.JMenu();
        javax.swing.JMenuItem BotaoMenuTelefoneContato = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuWhatsContato = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuEmailContato = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuSobre = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuAtualiSobre = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuDescontoSobre = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuNovasIntegSobre = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        jPanel1.setPreferredSize(new java.awt.Dimension(568, 612));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(19, 20, 39));
        jPanel5.setMinimumSize(new java.awt.Dimension(603, 130));
        jPanel5.setPreferredSize(new java.awt.Dimension(603, 130));

        btn_salvar_CadastroPF.setBackground(new java.awt.Color(0, 255, 204));
        btn_salvar_CadastroPF.setForeground(new java.awt.Color(0, 0, 0));
        btn_salvar_CadastroPF.setText("Salvar");
        btn_salvar_CadastroPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_CadastroPFActionPerformed(evt);
            }
        });

        btn_enviar_CadastroPF.setBackground(new java.awt.Color(0, 255, 51));
        btn_enviar_CadastroPF.setForeground(new java.awt.Color(0, 0, 0));
        btn_enviar_CadastroPF.setText("Enviar");

        btn_excluir.setBackground(new java.awt.Color(204, 0, 0));
        btn_excluir.setForeground(new java.awt.Color(0, 0, 0));
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btn_salvar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btn_enviar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Pessoa Jurídica");
        setMinimumSize(new java.awt.Dimension(570, 766));
        setResizable(false);
        getContentPane().setLayout(null);

        telaCadastroPJ.setBackground(new java.awt.Color(19, 20, 39));
        telaCadastroPJ.setToolTipText("");
        telaCadastroPJ.setMinimumSize(new java.awt.Dimension(603, 766));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro P.J");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Nome da Empresa:");

        CampNomeEmpreCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampNomeEmpreCadasPJActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("CNPJ:");

        campCNPJCadasPJ.setText("Informe o CNPJ");
        campCNPJCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campCNPJCadasPJActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Senha:");

        campSenhaCadasPJ.setText("Informe a senha");
        campSenhaCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campSenhaCadasPJActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/iconestoque.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cantarell", 1, 15), new java.awt.Color(51, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("CEP:");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("Bairro:");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("UF:");

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 255));
        jLabel10.setText("Rua:");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 255));
        jLabel11.setText("Nº:");

        campRuaCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campRuaCadasPJActionPerformed(evt);
            }
        });

        campUFCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campUFCadasPJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campUFCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campNumeRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campCEPCadasPJ)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(22, 22, 22)
                        .addComponent(campRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campBairroCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(campBairroCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campCEPCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(campNumeRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel9)
                        .addComponent(campUFCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnVoltarCadasPJ.setBackground(new java.awt.Color(204, 0, 0));
        btnVoltarCadasPJ.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltarCadasPJ.setText("Voltar");
        btnVoltarCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadasPJActionPerformed(evt);
            }
        });

        bntSalvarCadasPJ.setBackground(new java.awt.Color(0, 255, 204));
        bntSalvarCadasPJ.setForeground(new java.awt.Color(0, 0, 0));
        bntSalvarCadasPJ.setText("Salvar");
        bntSalvarCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarCadasPJActionPerformed(evt);
            }
        });

        bntEntrarCadasPJ.setBackground(new java.awt.Color(0, 255, 51));
        bntEntrarCadasPJ.setForeground(new java.awt.Color(0, 0, 0));
        bntEntrarCadasPJ.setText("Entrar");

        javax.swing.GroupLayout telaCadastroPJLayout = new javax.swing.GroupLayout(telaCadastroPJ);
        telaCadastroPJ.setLayout(telaCadastroPJLayout);
        telaCadastroPJLayout.setHorizontalGroup(
            telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroPJLayout.createSequentialGroup()
                .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campSenhaCadasPJ)
                                .addComponent(campCNPJCadasPJ)
                                .addComponent(CampNomeEmpreCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroPJLayout.createSequentialGroup()
                                    .addComponent(btnVoltarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(bntSalvarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntEntrarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        telaCadastroPJLayout.setVerticalGroup(
            telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroPJLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampNomeEmpreCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campCNPJCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(campSenhaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntEntrarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSalvarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(telaCadastroPJ);
        telaCadastroPJ.setBounds(0, -30, 570, 760);

        botaoMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/loginicon(1).png"))); // NOI18N
        botaoMenuUsuario.setText("Usuário");

        botaoMenuCadastreSeUsuarioPF.setText("Cadastre-se");
        botaoMenuCadastreSeUsuarioPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuCadastreSeUsuarioPFActionPerformed(evt);
            }
        });
        botaoMenuUsuario.add(botaoMenuCadastreSeUsuarioPF);

        botaoMenuEsqueUsuarioSenhaPF.setText("Esqueci minha senha");
        botaoMenuUsuario.add(botaoMenuEsqueUsuarioSenhaPF);

        botaoUsuarioMenuSairPF.setText("Sair");
        botaoUsuarioMenuSairPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUsuarioMenuSairPFActionPerformed(evt);
            }
        });
        botaoMenuUsuario.add(botaoUsuarioMenuSairPF);

        jMenuBar1.add(botaoMenuUsuario);

        botaoMenuCadastreSePJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/P.J.png"))); // NOI18N
        botaoMenuCadastreSePJ.setText("Pessoa Jurídica");

        botaoMenuLoginPJ.setText("Login");
        botaoMenuLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuLoginPJActionPerformed(evt);
            }
        });
        botaoMenuCadastreSePJ.add(botaoMenuLoginPJ);

        botaoMenuCadrasteSePJ.setText("Cadastre-se");
        botaoMenuCadrasteSePJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuCadrasteSePJActionPerformed(evt);
            }
        });
        botaoMenuCadastreSePJ.add(botaoMenuCadrasteSePJ);

        jMenuBar1.add(botaoMenuCadastreSePJ);

        botaoMenuContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/contact(1).png"))); // NOI18N
        botaoMenuContato.setText("Contato");

        BotaoMenuTelefoneContato.setText("Telefone");
        botaoMenuContato.add(BotaoMenuTelefoneContato);

        botaoMenuWhatsContato.setText("WhatsApp");
        botaoMenuContato.add(botaoMenuWhatsContato);

        botaoMenuEmailContato.setText("Email");
        botaoMenuContato.add(botaoMenuEmailContato);

        jMenuBar1.add(botaoMenuContato);

        botaoMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/sobreicon.png"))); // NOI18N
        botaoMenuSobre.setText("Sobre");

        botaoMenuAtualiSobre.setText("Atualizações");
        botaoMenuAtualiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuAtualiSobreActionPerformed(evt);
            }
        });
        botaoMenuSobre.add(botaoMenuAtualiSobre);

        botaoMenuDescontoSobre.setText("Descontos");
        botaoMenuSobre.add(botaoMenuDescontoSobre);

        botaoMenuNovasIntegSobre.setText("Novas integrações");
        botaoMenuSobre.add(botaoMenuNovasIntegSobre);

        jMenuBar1.add(botaoMenuSobre);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvar_CadastroPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_CadastroPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvar_CadastroPFActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Verificação", JOptionPane.YES_NO_OPTION);
        if (resposta==JOptionPane.YES_OPTION){
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void botaoMenuCadastreSeUsuarioPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuCadastreSeUsuarioPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuCadastreSeUsuarioPFActionPerformed

    private void botaoUsuarioMenuSairPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUsuarioMenuSairPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoUsuarioMenuSairPFActionPerformed

    private void botaoMenuCadrasteSePJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuCadrasteSePJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuCadrasteSePJActionPerformed

    private void botaoMenuLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuLoginPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuLoginPJActionPerformed

    private void botaoMenuAtualiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuAtualiSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuAtualiSobreActionPerformed

    private void bntSalvarCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSalvarCadasPJActionPerformed

    private void btnVoltarCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadasPJActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Verificação", JOptionPane.YES_NO_OPTION);
        if (resposta==JOptionPane.YES_OPTION){
            CampNomeEmpreCadasPJ.setText(" ");
            campSenhaCadasPJ.setText(" ");
        }
    }//GEN-LAST:event_btnVoltarCadasPJActionPerformed

    private void campRuaCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campRuaCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campRuaCadasPJActionPerformed

    private void campSenhaCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campSenhaCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campSenhaCadasPJActionPerformed

    private void campCNPJCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campCNPJCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campCNPJCadasPJActionPerformed

    private void CampNomeEmpreCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampNomeEmpreCadasPJActionPerformed

    }//GEN-LAST:event_CampNomeEmpreCadasPJActionPerformed

    private void campUFCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campUFCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campUFCadasPJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPJ_sdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField CampNomeEmpreCadasPJ;
    javax.swing.JFormattedTextField campSenhaCadasPJ;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JPanel telaCadastroPJ;
    // End of variables declaration//GEN-END:variables
}
