/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_interface.view;

import javax.swing.JOptionPane;

/**
 *
 * @author samueldouglasdossantos
 */
public class CadastroPF_sdi1 extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPF_sdi1
     */
    public CadastroPF_sdi1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        telaDeCadastroPF = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        CampCadasSenhaPF = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JButton btnEntrarCadasPF = new javax.swing.JButton();
        javax.swing.JButton btnSalvaCadasPF = new javax.swing.JButton();
        javax.swing.JButton btnVoltarCadasPF = new javax.swing.JButton();
        javax.swing.JFormattedTextField CampCPFCadasPF = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JFormattedTextField CampEmailCadasPF = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        MenuSexoCadasPF = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        compNomeComCadasPF = new javax.swing.JTextField();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu MenoUsuario = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuCadastreSeUsuarioPF = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuEsqueUsuarioSenhaPF = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuCadastreSePJ = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuCadrasteSePJ = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuLoginSePJ = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuTelefoneSePJ = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuTelefonePJ = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuWhatsappPJ = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem7 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CadastroSDI");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 746, -1, -1));

        telaDeCadastroPF.setBackground(new java.awt.Color(19, 20, 39));
        telaDeCadastroPF.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro P.F");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Nome completo:");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("CPF:");

        CampCadasSenhaPF.setText("jPasswordField1");

        btnEntrarCadasPF.setBackground(new java.awt.Color(0, 255, 51));
        btnEntrarCadasPF.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrarCadasPF.setText("Entrar");

        btnSalvaCadasPF.setBackground(new java.awt.Color(0, 255, 204));
        btnSalvaCadasPF.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvaCadasPF.setText("Salvar");
        btnSalvaCadasPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaCadasPFActionPerformed(evt);
            }
        });

        btnVoltarCadasPF.setBackground(new java.awt.Color(204, 0, 0));
        btnVoltarCadasPF.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltarCadasPF.setText("Voltar");
        btnVoltarCadasPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadasPFActionPerformed(evt);
            }
        });

        CampCPFCadasPF.setText("Informe seu CPF");
        CampCPFCadasPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampCPFCadasPFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Email:");

        CampEmailCadasPF.setText("Informe seu E-mail");
        CampEmailCadasPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampEmailCadasPFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Seu gênero:");

        MenuSexoCadasPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outros" }));
        MenuSexoCadasPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSexoCadasPFActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/iconestoque.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        compNomeComCadasPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compNomeComCadasPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaDeCadastroPFLayout = new javax.swing.GroupLayout(telaDeCadastroPF);
        telaDeCadastroPF.setLayout(telaDeCadastroPFLayout);
        telaDeCadastroPFLayout.setHorizontalGroup(
            telaDeCadastroPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeCadastroPFLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(telaDeCadastroPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaDeCadastroPFLayout.createSequentialGroup()
                        .addComponent(btnVoltarCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvaCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnEntrarCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaDeCadastroPFLayout.createSequentialGroup()
                        .addComponent(CampCadasSenhaPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuSexoCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(telaDeCadastroPFLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(telaDeCadastroPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(compNomeComCadasPF)
                    .addComponent(jLabel4)
                    .addComponent(CampCPFCadasPF, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(CampEmailCadasPF))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(telaDeCadastroPFLayout.createSequentialGroup()
                .addGroup(telaDeCadastroPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeCadastroPFLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(telaDeCadastroPFLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaDeCadastroPFLayout.setVerticalGroup(
            telaDeCadastroPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeCadastroPFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(compNomeComCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampCPFCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampEmailCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDeCadastroPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampCadasSenhaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(MenuSexoCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(telaDeCadastroPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrarCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvaCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltarCadasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(telaDeCadastroPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 584, 710));

        MenoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/loginicon(1).png"))); // NOI18N
        MenoUsuario.setText("Usuário");

        botaoMenuCadastreSeUsuarioPF.setText("Cadastre-se");
        botaoMenuCadastreSeUsuarioPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuCadastreSeUsuarioPFActionPerformed(evt);
            }
        });
        MenoUsuario.add(botaoMenuCadastreSeUsuarioPF);

        botaoMenuEsqueUsuarioSenhaPF.setText("Esqueci minha senha");
        MenoUsuario.add(botaoMenuEsqueUsuarioSenhaPF);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenoUsuario.add(jMenuItem2);

        jMenuBar1.add(MenoUsuario);

        botaoMenuCadastreSePJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/P.J.png"))); // NOI18N
        botaoMenuCadastreSePJ.setText("Pessoa Jurídica");

        botaoMenuCadrasteSePJ.setText("Cadastre-se");
        botaoMenuCadrasteSePJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuCadrasteSePJActionPerformed(evt);
            }
        });
        botaoMenuCadastreSePJ.add(botaoMenuCadrasteSePJ);

        botaoMenuLoginSePJ.setText("Login");
        botaoMenuLoginSePJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuLoginSePJActionPerformed(evt);
            }
        });
        botaoMenuCadastreSePJ.add(botaoMenuLoginSePJ);

        jMenuBar1.add(botaoMenuCadastreSePJ);

        botaoMenuTelefoneSePJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/contact(1).png"))); // NOI18N
        botaoMenuTelefoneSePJ.setText("Contato");

        botaoMenuTelefonePJ.setText("Telefone");
        botaoMenuTelefoneSePJ.add(botaoMenuTelefonePJ);

        botaoMenuWhatsappPJ.setText("WhatsApp");
        botaoMenuTelefoneSePJ.add(botaoMenuWhatsappPJ);

        jMenuItem5.setText("Email");
        botaoMenuTelefoneSePJ.add(jMenuItem5);

        jMenuBar1.add(botaoMenuTelefoneSePJ);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/sobreicon.png"))); // NOI18N
        jMenu4.setText("Sobre");

        jMenuItem6.setText("Atualizações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Descontos");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Novas integrações");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarCadasPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadasPFActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Verificação", JOptionPane.YES_NO_OPTION);
        if (resposta==JOptionPane.YES_OPTION){
            compNomeComCadasPF.setText(" ");
            CampCadasSenhaPF.setText(" ");
        }
    }//GEN-LAST:event_btnVoltarCadasPFActionPerformed

    private void CampCPFCadasPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampCPFCadasPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampCPFCadasPFActionPerformed

    private void botaoMenuCadastreSeUsuarioPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuCadastreSeUsuarioPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuCadastreSeUsuarioPFActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void botaoMenuCadrasteSePJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuCadrasteSePJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuCadrasteSePJActionPerformed

    private void botaoMenuLoginSePJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuLoginSePJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuLoginSePJActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void CampEmailCadasPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampEmailCadasPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampEmailCadasPFActionPerformed

    private void MenuSexoCadasPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSexoCadasPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSexoCadasPFActionPerformed

    private void btnSalvaCadasPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaCadasPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvaCadasPFActionPerformed

    private void compNomeComCadasPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compNomeComCadasPFActionPerformed

    }//GEN-LAST:event_compNomeComCadasPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPF_sdi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPF_sdi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPF_sdi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPF_sdi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPF_sdi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPasswordField CampCadasSenhaPF;
    javax.swing.JComboBox<String> MenuSexoCadasPF;
    javax.swing.JTextField compNomeComCadasPF;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JPanel telaDeCadastroPF;
    // End of variables declaration//GEN-END:variables
}
