/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_interface.view;

import javax.swing.JOptionPane;
import project_interface.model.UsuarioPJ;
import project_interface.util.BDuserPJ;

/**
 *
 * @author samueldouglasdossantos
 */
public class CadastroPJ_sdi extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPJ_sdi
     */
    public CadastroPJ_sdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JButton btn_salvar_CadastroPF = new javax.swing.JButton();
        javax.swing.JButton btn_enviar_CadastroPF = new javax.swing.JButton();
        javax.swing.JButton btn_excluir = new javax.swing.JButton();
        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.ButtonGroup buttonGroup2 = new javax.swing.ButtonGroup();
        telaCadastroPJ = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        CampNomeEmpreCadasPJ = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        camEmailPJ = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        campCEPCadasPJ = new javax.swing.JFormattedTextField();
        campRuaCadasPJ = new javax.swing.JTextField();
        campBairroCadasPJ = new javax.swing.JTextField();
        campNumeRuaCadasPJ = new javax.swing.JTextField();
        campUFCadasPJ = new javax.swing.JTextField();
        javax.swing.JButton btnVoltarCadasPJ = new javax.swing.JButton();
        javax.swing.JButton bntSalvarCadasPJ = new javax.swing.JButton();
        javax.swing.JButton bntEntrarCadasPJ = new javax.swing.JButton();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        campCNPJCadasPJ1 = new javax.swing.JFormattedTextField();
        campSenhaPJ = new javax.swing.JPasswordField();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu botaoMenuUsuario = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuCadastreSeUsuarioPF = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuEsqueUsuarioSenhaPF = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoUsuarioMenuSairPF = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuCadastreSePJ = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuLoginPJ = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuCadrasteSePJ = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuContato = new javax.swing.JMenu();
        javax.swing.JMenuItem BotaoMenuTelefoneContato = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuWhatsContato = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuEmailContato = new javax.swing.JMenuItem();
        javax.swing.JMenu botaoMenuSobre = new javax.swing.JMenu();
        javax.swing.JMenuItem botaoMenuAtualiSobre = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuDescontoSobre = new javax.swing.JMenuItem();
        javax.swing.JMenuItem botaoMenuNovasIntegSobre = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        jPanel1.setPreferredSize(new java.awt.Dimension(568, 612));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(19, 20, 39));
        jPanel5.setMinimumSize(new java.awt.Dimension(603, 130));
        jPanel5.setPreferredSize(new java.awt.Dimension(603, 130));

        btn_salvar_CadastroPF.setBackground(new java.awt.Color(0, 255, 204));
        btn_salvar_CadastroPF.setForeground(new java.awt.Color(0, 0, 0));
        btn_salvar_CadastroPF.setText("Salvar");
        btn_salvar_CadastroPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_CadastroPFActionPerformed(evt);
            }
        });

        btn_enviar_CadastroPF.setBackground(new java.awt.Color(0, 255, 51));
        btn_enviar_CadastroPF.setForeground(new java.awt.Color(0, 0, 0));
        btn_enviar_CadastroPF.setText("Enviar");

        btn_excluir.setBackground(new java.awt.Color(204, 0, 0));
        btn_excluir.setForeground(new java.awt.Color(0, 0, 0));
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btn_salvar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btn_enviar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviar_CadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoa Jurídica");
        setMinimumSize(new java.awt.Dimension(570, 820));
        setResizable(false);
        getContentPane().setLayout(null);

        telaCadastroPJ.setBackground(new java.awt.Color(19, 20, 39));
        telaCadastroPJ.setToolTipText("");
        telaCadastroPJ.setMinimumSize(new java.awt.Dimension(603, 766));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro P.J");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Nome da Empresa:");

        CampNomeEmpreCadasPJ.setText("Digite o nome da empresa:");
        CampNomeEmpreCadasPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampNomeEmpreCadasPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampNomeEmpreCadasPJFocusLost(evt);
            }
        });
        CampNomeEmpreCadasPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampNomeEmpreCadasPJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CampNomeEmpreCadasPJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CampNomeEmpreCadasPJMouseExited(evt);
            }
        });
        CampNomeEmpreCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampNomeEmpreCadasPJActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("CNPJ:");

        camEmailPJ.setText("Digite seu email:");
        camEmailPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                camEmailPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                camEmailPJFocusLost(evt);
            }
        });
        camEmailPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                camEmailPJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                camEmailPJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                camEmailPJMouseExited(evt);
            }
        });
        camEmailPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camEmailPJActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Email:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/iconestoque.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cantarell", 1, 15), new java.awt.Color(51, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("CEP:");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("Bairro:");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("UF:");

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 255));
        jLabel10.setText("Rua:");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 255));
        jLabel11.setText("Nº:");

        try {
            campCEPCadasPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campCEPCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campCEPCadasPJActionPerformed(evt);
            }
        });

        campRuaCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campRuaCadasPJActionPerformed(evt);
            }
        });

        campUFCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campUFCadasPJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campUFCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campNumeRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campCEPCadasPJ)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(22, 22, 22)
                        .addComponent(campRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campBairroCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(campBairroCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campCEPCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(campNumeRuaCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel9)
                        .addComponent(campUFCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnVoltarCadasPJ.setBackground(new java.awt.Color(204, 0, 0));
        btnVoltarCadasPJ.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltarCadasPJ.setText("Voltar");
        btnVoltarCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadasPJActionPerformed(evt);
            }
        });

        bntSalvarCadasPJ.setBackground(new java.awt.Color(0, 255, 204));
        bntSalvarCadasPJ.setForeground(new java.awt.Color(0, 0, 0));
        bntSalvarCadasPJ.setText("Salvar");
        bntSalvarCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarCadasPJActionPerformed(evt);
            }
        });

        bntEntrarCadasPJ.setBackground(new java.awt.Color(0, 255, 51));
        bntEntrarCadasPJ.setForeground(new java.awt.Color(0, 0, 0));
        bntEntrarCadasPJ.setText("Entrar");
        bntEntrarCadasPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEntrarCadasPJActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 255));
        jLabel12.setText("Senha:");

        campCNPJCadasPJ1.setText("Informe o CNPJ:");
        campCNPJCadasPJ1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campCNPJCadasPJ1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campCNPJCadasPJ1FocusLost(evt);
            }
        });
        campCNPJCadasPJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campCNPJCadasPJ1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campCNPJCadasPJ1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campCNPJCadasPJ1MouseExited(evt);
            }
        });
        campCNPJCadasPJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campCNPJCadasPJ1ActionPerformed(evt);
            }
        });

        campSenhaPJ.setText("jPasswordField1");

        javax.swing.GroupLayout telaCadastroPJLayout = new javax.swing.GroupLayout(telaCadastroPJ);
        telaCadastroPJ.setLayout(telaCadastroPJLayout);
        telaCadastroPJLayout.setHorizontalGroup(
            telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroPJLayout.createSequentialGroup()
                .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(CampNomeEmpreCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(campCNPJCadasPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroPJLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campSenhaPJ, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaCadastroPJLayout.createSequentialGroup()
                                    .addComponent(btnVoltarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(bntSalvarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntEntrarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(camEmailPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        telaCadastroPJLayout.setVerticalGroup(
            telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroPJLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(CampNomeEmpreCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(campCNPJCadasPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(camEmailPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campSenhaPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(telaCadastroPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalvarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntEntrarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltarCadasPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(telaCadastroPJ);
        telaCadastroPJ.setBounds(0, -30, 570, 790);

        botaoMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/loginicon(1).png"))); // NOI18N
        botaoMenuUsuario.setText("Usuário");
        botaoMenuUsuario.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                botaoMenuUsuarioHierarchyChanged(evt);
            }
        });
        botaoMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuUsuarioActionPerformed(evt);
            }
        });

        botaoMenuCadastreSeUsuarioPF.setText("Cadastre-se");
        botaoMenuCadastreSeUsuarioPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuCadastreSeUsuarioPFActionPerformed(evt);
            }
        });
        botaoMenuUsuario.add(botaoMenuCadastreSeUsuarioPF);

        botaoMenuEsqueUsuarioSenhaPF.setText("Esqueci minha senha");
        botaoMenuUsuario.add(botaoMenuEsqueUsuarioSenhaPF);

        botaoUsuarioMenuSairPF.setText("Sair");
        botaoUsuarioMenuSairPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUsuarioMenuSairPFActionPerformed(evt);
            }
        });
        botaoMenuUsuario.add(botaoUsuarioMenuSairPF);

        jMenuBar1.add(botaoMenuUsuario);

        botaoMenuCadastreSePJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/P.J.png"))); // NOI18N
        botaoMenuCadastreSePJ.setText("Pessoa Jurídica");

        botaoMenuLoginPJ.setText("Login");
        botaoMenuLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuLoginPJActionPerformed(evt);
            }
        });
        botaoMenuCadastreSePJ.add(botaoMenuLoginPJ);

        botaoMenuCadrasteSePJ.setText("Cadastre-se");
        botaoMenuCadrasteSePJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuCadrasteSePJActionPerformed(evt);
            }
        });
        botaoMenuCadastreSePJ.add(botaoMenuCadrasteSePJ);

        jMenuBar1.add(botaoMenuCadastreSePJ);

        botaoMenuContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/contact(1).png"))); // NOI18N
        botaoMenuContato.setText("Contato");

        BotaoMenuTelefoneContato.setText("Telefone");
        botaoMenuContato.add(BotaoMenuTelefoneContato);

        botaoMenuWhatsContato.setText("WhatsApp");
        botaoMenuContato.add(botaoMenuWhatsContato);

        botaoMenuEmailContato.setText("Email");
        botaoMenuContato.add(botaoMenuEmailContato);

        jMenuBar1.add(botaoMenuContato);

        botaoMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/sobreicon.png"))); // NOI18N
        botaoMenuSobre.setText("Sobre");

        botaoMenuAtualiSobre.setText("Atualizações");
        botaoMenuAtualiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuAtualiSobreActionPerformed(evt);
            }
        });
        botaoMenuSobre.add(botaoMenuAtualiSobre);

        botaoMenuDescontoSobre.setText("Descontos");
        botaoMenuSobre.add(botaoMenuDescontoSobre);

        botaoMenuNovasIntegSobre.setText("Novas integrações");
        botaoMenuSobre.add(botaoMenuNovasIntegSobre);

        jMenuBar1.add(botaoMenuSobre);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvar_CadastroPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_CadastroPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvar_CadastroPFActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Verificação", JOptionPane.YES_NO_OPTION);
        if (resposta==JOptionPane.YES_OPTION){
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void botaoMenuCadastreSeUsuarioPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuCadastreSeUsuarioPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuCadastreSeUsuarioPFActionPerformed

    private void botaoUsuarioMenuSairPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUsuarioMenuSairPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoUsuarioMenuSairPFActionPerformed

    private void botaoMenuCadrasteSePJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuCadrasteSePJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuCadrasteSePJActionPerformed

    private void botaoMenuLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuLoginPJActionPerformed
        new LoginPJ_sdi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoMenuLoginPJActionPerformed

    private void botaoMenuAtualiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuAtualiSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuAtualiSobreActionPerformed

    private void bntSalvarCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSalvarCadasPJActionPerformed

    private void btnVoltarCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadasPJActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Voltar pode acarretar a exclusão de seus dados. Deseja prosseguir?", "Verificação", JOptionPane.YES_NO_OPTION);
            if (resposta==JOptionPane.YES_OPTION){
                this.dispose();
            }
    }//GEN-LAST:event_btnVoltarCadasPJActionPerformed

    private void campRuaCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campRuaCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campRuaCadasPJActionPerformed

    private void camEmailPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camEmailPJActionPerformed
        if(CampNomeEmpreCadasPJ.getText().equals("Digite o nome da empresa:")){
            CampNomeEmpreCadasPJ.setText(" ");
        }
        else if(CampNomeEmpreCadasPJ.getText().equals(" ")){
            CampNomeEmpreCadasPJ.setText("Digite o nome da empresa:");
        }
    }//GEN-LAST:event_camEmailPJActionPerformed

    private void CampNomeEmpreCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampNomeEmpreCadasPJActionPerformed
        
    }//GEN-LAST:event_CampNomeEmpreCadasPJActionPerformed

    private void campUFCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campUFCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campUFCadasPJActionPerformed

    private void campCEPCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campCEPCadasPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campCEPCadasPJActionPerformed

    private void bntEntrarCadasPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEntrarCadasPJActionPerformed
    String nomeEmpresa = CampNomeEmpreCadasPJ.getText();
    String cnpj = campCNPJCadasPJ1.getText(); 
    String email = camEmailPJ.getText(); 
    String senha = new String(campSenhaPJ.getPassword()); 
    String cep = campCEPCadasPJ.getText(); 
    String bairro = campBairroCadasPJ.getText();
    String uf = campUFCadasPJ.getText(); 
    String rua = campRuaCadasPJ.getText();
    int numero = Integer.parseInt(campNumeRuaCadasPJ.getText());

    // Verificação de campos obrigatórios
    if (nomeEmpresa.isEmpty() || cnpj.isEmpty() || email.isEmpty() || senha.isEmpty() || cep.isEmpty() || bairro.isEmpty() || uf.isEmpty() || rua.isEmpty() || campNumeRuaCadasPJ.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        return;
    }

    // Criando um novo objeto UsuarioPJ com os dados obtidos
    UsuarioPJ usuarioPJ = new UsuarioPJ(nomeEmpresa, cnpj, email, senha, cep, bairro, uf, numero, rua);

    boolean sucesso = BDuserPJ.inserirUsuario(usuarioPJ);

    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
        limparCampos(); // Limpa os campos após cadastro (opcional)
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao realizar o cadastro. Verifique os dados e tente novamente.");
    }
}

private void limparCampos() {
    CampNomeEmpreCadasPJ.setText("");
    campCNPJCadasPJ1.setText("");
    camEmailPJ.setText("");
    campSenhaPJ.setText("");
    campCEPCadasPJ.setText("");
    campBairroCadasPJ.setText("");
    campUFCadasPJ.setText("");
    campRuaCadasPJ.setText("");
    campNumeRuaCadasPJ.setText("");
    }//GEN-LAST:event_bntEntrarCadasPJActionPerformed

    private void CampNomeEmpreCadasPJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampNomeEmpreCadasPJMouseClicked
        
        
    }//GEN-LAST:event_CampNomeEmpreCadasPJMouseClicked

    private void CampNomeEmpreCadasPJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampNomeEmpreCadasPJMouseExited
        
    }//GEN-LAST:event_CampNomeEmpreCadasPJMouseExited

    private void CampNomeEmpreCadasPJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampNomeEmpreCadasPJMouseEntered
        
    }//GEN-LAST:event_CampNomeEmpreCadasPJMouseEntered

    private void camEmailPJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camEmailPJMouseClicked
        
    }//GEN-LAST:event_camEmailPJMouseClicked

    private void camEmailPJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camEmailPJMouseEntered
        
    }//GEN-LAST:event_camEmailPJMouseEntered

    private void camEmailPJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camEmailPJMouseExited
        
    }//GEN-LAST:event_camEmailPJMouseExited

    private void botaoMenuUsuarioHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_botaoMenuUsuarioHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuUsuarioHierarchyChanged

    private void botaoMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMenuUsuarioActionPerformed

    private void CampNomeEmpreCadasPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampNomeEmpreCadasPJFocusGained
        if (CampNomeEmpreCadasPJ.getText().equals("Digite o nome da empresa:")) {
            CampNomeEmpreCadasPJ.setText("");
        }
    }//GEN-LAST:event_CampNomeEmpreCadasPJFocusGained

    private void camEmailPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_camEmailPJFocusGained
        if (camEmailPJ.getText().equals("Digite seu email:")) {
            camEmailPJ.setText("");
        }
    }//GEN-LAST:event_camEmailPJFocusGained

    private void CampNomeEmpreCadasPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampNomeEmpreCadasPJFocusLost
        if (CampNomeEmpreCadasPJ.getText().isEmpty()) {
            CampNomeEmpreCadasPJ.setText("Digite o nome da empresa:");
        }
    }//GEN-LAST:event_CampNomeEmpreCadasPJFocusLost

    private void camEmailPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_camEmailPJFocusLost
        if (camEmailPJ.getText().isEmpty()) {
            camEmailPJ.setText("Digite seu email:");
        }
    }//GEN-LAST:event_camEmailPJFocusLost

    private void campCNPJCadasPJ1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campCNPJCadasPJ1FocusGained
        if (campCNPJCadasPJ1.getText().equals("Informe o CNPJ:")){
            campCNPJCadasPJ1.setText("");
        }
    }//GEN-LAST:event_campCNPJCadasPJ1FocusGained

    private void campCNPJCadasPJ1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campCNPJCadasPJ1FocusLost
        if (campCNPJCadasPJ1.getText().isEmpty()){
            campCNPJCadasPJ1.setText("Informe o CNPJ:");
        }
    }//GEN-LAST:event_campCNPJCadasPJ1FocusLost

    private void campCNPJCadasPJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campCNPJCadasPJ1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campCNPJCadasPJ1MouseClicked

    private void campCNPJCadasPJ1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campCNPJCadasPJ1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_campCNPJCadasPJ1MouseEntered

    private void campCNPJCadasPJ1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campCNPJCadasPJ1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_campCNPJCadasPJ1MouseExited

    private void campCNPJCadasPJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campCNPJCadasPJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campCNPJCadasPJ1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        BDuserPJ.criarTabelas();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPJ_sdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField CampNomeEmpreCadasPJ;
    javax.swing.JFormattedTextField camEmailPJ;
    javax.swing.JTextField campBairroCadasPJ;
    javax.swing.JFormattedTextField campCEPCadasPJ;
    javax.swing.JFormattedTextField campCNPJCadasPJ1;
    javax.swing.JTextField campNumeRuaCadasPJ;
    javax.swing.JTextField campRuaCadasPJ;
    javax.swing.JPasswordField campSenhaPJ;
    javax.swing.JTextField campUFCadasPJ;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JPanel telaCadastroPJ;
    // End of variables declaration//GEN-END:variables
}
