/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_interface.view;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project_interface.util.BDuserPF;
import project_interface.model.UsuarioPF;
/**
 *
 * @author samueldouglasdossantos
 */
public class GerenciamentoUsuariosPF extends javax.swing.JFrame {

    /**
     * Creates new form GerenciamentoUsuariosPF
     */
    public GerenciamentoUsuariosPF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        TextPreço2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JButton editarUser = new javax.swing.JButton();
        javax.swing.JButton excluirUser = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        tabelaUsuariosPF = new javax.swing.JTable();
        javax.swing.JButton atualizarUser = new javax.swing.JButton();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu CadastrePJMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem11 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem esqueciSenhaMenu = new javax.swing.JMenuItem();
        javax.swing.JMenuItem sairMenu = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem7 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        TextPreço2.setBackground(new java.awt.Color(19, 20, 39));
        TextPreço2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Controle de Usuários:");

        editarUser.setBackground(new java.awt.Color(0, 255, 0));
        editarUser.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        editarUser.setText("Editar dados");
        editarUser.setMaximumSize(new java.awt.Dimension(75, 25));
        editarUser.setMinimumSize(new java.awt.Dimension(75, 25));
        editarUser.setPreferredSize(new java.awt.Dimension(125, 30));
        editarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUserActionPerformed(evt);
            }
        });

        excluirUser.setBackground(new java.awt.Color(204, 102, 0));
        excluirUser.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        excluirUser.setText("Excluir usuário");
        excluirUser.setMaximumSize(new java.awt.Dimension(75, 25));
        excluirUser.setMinimumSize(new java.awt.Dimension(75, 25));
        excluirUser.setPreferredSize(new java.awt.Dimension(125, 30));
        excluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUserActionPerformed(evt);
            }
        });

        tabelaUsuariosPF.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {
                "Id", "Nome:", "CPF:", "Email:", "Gênero:"
            }
        ) {
            // Tipo das colunas
            Class[] types = new Class[] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            // Define se as células são editáveis
            boolean[] canEdit = new boolean[] {
                false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        //chamando o método que retorna a matriz bidimensional (array dentro do array)
        Object[][] dadosUsuarios = BDuserPF.obterDadosUsuarios();
        //modelo padrão, da table, pra gerenciar dados (modificado como "modelo" para uso no acréscimo de linhas)
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaUsuariosPF.getModel();
        // Adiciona cada linha (registro) ao modelo da tabela
        for (Object[] linha : dadosUsuarios) {
            modelo.addRow(linha);
        }
        // Desativa o redimensionamento das linhas
        tabelaUsuariosPF.getTableHeader().setResizingAllowed(false);
        // Desativa o reordenamento das colunas
        tabelaUsuariosPF.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaUsuariosPF);

        atualizarUser.setBackground(new java.awt.Color(51, 51, 255));
        atualizarUser.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        atualizarUser.setText("Atualizar");
        atualizarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TextPreço2Layout = new javax.swing.GroupLayout(TextPreço2);
        TextPreço2.setLayout(TextPreço2Layout);
        TextPreço2Layout.setHorizontalGroup(
            TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreço2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreço2Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPreço2Layout.createSequentialGroup()
                        .addComponent(excluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(atualizarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(editarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        TextPreço2Layout.setVerticalGroup(
            TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPreço2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextPreço2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(TextPreço2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CadastrePJMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/P.J.png"))); // NOI18N
        CadastrePJMenu.setText("Pessoa Jurídica");

        jMenuItem11.setText("Cadastre-se");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        CadastrePJMenu.add(jMenuItem11);

        esqueciSenhaMenu.setText("Esqueci minha senha");
        esqueciSenhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqueciSenhaMenuActionPerformed(evt);
            }
        });
        CadastrePJMenu.add(esqueciSenhaMenu);

        sairMenu.setText("Sair");
        sairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuActionPerformed(evt);
            }
        });
        CadastrePJMenu.add(sairMenu);

        jMenuBar1.add(CadastrePJMenu);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/contact(1).png"))); // NOI18N
        jMenu2.setText("Contato");

        jMenuItem3.setText("Telefone");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("WhatsApp");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Email");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/sobreicon.png"))); // NOI18N
        jMenu4.setText("Sobre");

        jMenuItem6.setText("Atualizações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Descontos");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Novas integrações");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUserActionPerformed
        
        int linhaSelecionada = tabelaUsuariosPF.getSelectedRow();        
        //a partir de qual index deve ser obtida a linha da :
        if (linhaSelecionada >= 0) {
            // Obtém os dados da linha selecionada
            String nomeAtual = (String) tabelaUsuariosPF.getValueAt(linhaSelecionada, 1);
            String cpfAtual = (String) tabelaUsuariosPF.getValueAt(linhaSelecionada, 2);
            String emailAtual = (String) tabelaUsuariosPF.getValueAt(linhaSelecionada, 3);
            String generoAtual = (String) tabelaUsuariosPF.getValueAt(linhaSelecionada, 4);

            // Alteração de dados por meio de caixas de diálogo
            String novoNome = JOptionPane.showInputDialog(this, "Editar Nome:", nomeAtual);
            String novoCpf = JOptionPane.showInputDialog(this, "Editar CPF:", cpfAtual);
            String novoEmail = JOptionPane.showInputDialog(this, "Editar Email:", emailAtual);
            String novoGenero = JOptionPane.showInputDialog(this, "Editar Gênero:", generoAtual);

            // Verifica se as informações 
            if (novoNome != null && novoEmail != null && novoGenero != null) {
                if (BDuserPF.editarUsuario(novoNome, novoEmail, novoCpf, novoGenero, cpfAtual)) {  // Passando cpfAtual
                    JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso.");
                    // Atualiza a tabela diretamente
                    tabelaUsuariosPF.setValueAt(novoNome, linhaSelecionada, 1);
                    tabelaUsuariosPF.setValueAt(novoCpf, linhaSelecionada, 2);
                    tabelaUsuariosPF.setValueAt(novoEmail, linhaSelecionada, 3);
                    tabelaUsuariosPF.setValueAt(novoGenero, linhaSelecionada, 4);
            }else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar o usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            }
        }else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_editarUserActionPerformed

    private void excluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUserActionPerformed
        int linhaSelecionada = tabelaUsuariosPF.getSelectedRow();
        if (linhaSelecionada >= 0) {
            String cpf = (String) tabelaUsuariosPF.getValueAt(linhaSelecionada, 2); // Coluna do CPF
            //variável pro OptionPane, para receber a mensagem yes ou no
            int confirmacao = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir o usuário com CPF " + cpf + "?",
            "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                if (BDuserPF.excluirUsuario(cpf)) {
                    JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso.");
                    ((DefaultTableModel) tabelaUsuariosPF.getModel()).removeRow(linhaSelecionada);
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao excluir o usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
        JOptionPane.showMessageDialog(this, "Selecione um usuário na tabela.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_excluirUserActionPerformed

    private void atualizarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarUserActionPerformed
        // Recupera os dados atualizados do banco de dados
        Object[][] dadosAtualizados = BDuserPF.obterDadosUsuarios();

        // Atualiza a tabela com novos dados
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaUsuariosPF.getModel();
        modeloTabela.setRowCount(0);  // Limpa as linhas da tabela

        // Adiciona os dados atualizados
        for (Object[] linha : dadosAtualizados) {
            modeloTabela.addRow(linha);
        }

        JOptionPane.showMessageDialog(this, "Dados atualizados");
    }//GEN-LAST:event_atualizarUserActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void esqueciSenhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqueciSenhaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esqueciSenhaMenuActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void sairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoUsuariosPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoUsuariosPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoUsuariosPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoUsuariosPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoUsuariosPF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel TextPreço2;
    javax.swing.JTable tabelaUsuariosPF;
    // End of variables declaration//GEN-END:variables
}
