/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_interface.view;

import javax.swing.JOptionPane;

/**
 *
 * @author samueldouglasdossantos
 */
public class LoginPJ_sdi extends javax.swing.JFrame {

    /**
     * Creates new form LoginPJ_sdi
     */
    public LoginPJ_sdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDeAcessoLoginPJ = new javax.swing.JPanel();
        btnVoltarLoginPJ = new javax.swing.JButton();
        CampSenhaLoginPJ = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        campEmailLoginPJ = new javax.swing.JTextField();
        checkBoxLembrarLoginPJ = new javax.swing.JCheckBox();
        javax.swing.JButton btnEntrarLoginPJ = new javax.swing.JButton();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JButton btnEsqueceuSenhaLoginPJ = new javax.swing.JButton();
        javax.swing.JLabel linkLabel = new javax.swing.JLabel();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem9 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu5 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem11 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem12 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem7 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        telaDeAcessoLoginPJ.setBackground(new java.awt.Color(19, 20, 39));
        telaDeAcessoLoginPJ.setToolTipText("");
        telaDeAcessoLoginPJ.setPreferredSize(new java.awt.Dimension(437, 672));

        btnVoltarLoginPJ.setBackground(new java.awt.Color(255, 0, 0));
        btnVoltarLoginPJ.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnVoltarLoginPJ.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltarLoginPJ.setText("Voltar");
        btnVoltarLoginPJ.setMaximumSize(new java.awt.Dimension(125, 25));
        btnVoltarLoginPJ.setMinimumSize(new java.awt.Dimension(125, 25));
        btnVoltarLoginPJ.setPreferredSize(new java.awt.Dimension(125, 30));
        btnVoltarLoginPJ.setSelected(true);
        btnVoltarLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLoginPJActionPerformed(evt);
            }
        });

        CampSenhaLoginPJ.setText("*******");
        CampSenhaLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampSenhaLoginPJActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Senha:");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Login:");

        campEmailLoginPJ.setText("Digite seu login");
        campEmailLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campEmailLoginPJActionPerformed(evt);
            }
        });

        checkBoxLembrarLoginPJ.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        checkBoxLembrarLoginPJ.setForeground(new java.awt.Color(51, 255, 255));
        checkBoxLembrarLoginPJ.setText("Lembrar Login.");
        checkBoxLembrarLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLembrarLoginPJActionPerformed(evt);
            }
        });

        btnEntrarLoginPJ.setBackground(new java.awt.Color(0, 255, 0));
        btnEntrarLoginPJ.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnEntrarLoginPJ.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrarLoginPJ.setText("Entrar");
        btnEntrarLoginPJ.setMaximumSize(new java.awt.Dimension(75, 25));
        btnEntrarLoginPJ.setMinimumSize(new java.awt.Dimension(75, 25));
        btnEntrarLoginPJ.setPreferredSize(new java.awt.Dimension(125, 30));
        btnEntrarLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarLoginPJActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/iconestoque.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Acesso P.J");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setMinimumSize(new java.awt.Dimension(66, 25));

        btnEsqueceuSenhaLoginPJ.setBackground(new java.awt.Color(0, 255, 203));
        btnEsqueceuSenhaLoginPJ.setForeground(new java.awt.Color(0, 0, 0));
        btnEsqueceuSenhaLoginPJ.setText("Clique aqui!");
        btnEsqueceuSenhaLoginPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueceuSenhaLoginPJActionPerformed(evt);
            }
        });

        linkLabel.setForeground(new java.awt.Color(255, 255, 255));
        linkLabel.setText("Esqueceu sua senha? ");
        linkLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                linkLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout telaDeAcessoLoginPJLayout = new javax.swing.GroupLayout(telaDeAcessoLoginPJ);
        telaDeAcessoLoginPJ.setLayout(telaDeAcessoLoginPJLayout);
        telaDeAcessoLoginPJLayout.setHorizontalGroup(
            telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLoginPJLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLoginPJLayout.createSequentialGroup()
                                    .addComponent(linkLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEsqueceuSenhaLoginPJ)
                                    .addGap(78, 78, 78))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLoginPJLayout.createSequentialGroup()
                                    .addComponent(campEmailLoginPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLoginPJLayout.createSequentialGroup()
                            .addComponent(CampSenhaLoginPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(telaDeAcessoLoginPJLayout.createSequentialGroup()
                        .addGroup(telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDeAcessoLoginPJLayout.createSequentialGroup()
                                .addComponent(btnVoltarLoginPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(btnEntrarLoginPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkBoxLembrarLoginPJ))
                        .addContainerGap(72, Short.MAX_VALUE))))
            .addGroup(telaDeAcessoLoginPJLayout.createSequentialGroup()
                .addGroup(telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeAcessoLoginPJLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaDeAcessoLoginPJLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        telaDeAcessoLoginPJLayout.setVerticalGroup(
            telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeAcessoLoginPJLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campEmailLoginPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CampSenhaLoginPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkBoxLembrarLoginPJ)
                .addGap(57, 57, 57)
                .addGroup(telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarLoginPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntrarLoginPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(telaDeAcessoLoginPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkLabel)
                    .addComponent(btnEsqueceuSenhaLoginPJ))
                .addGap(53, 53, 53))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/loginicon(1).png"))); // NOI18N
        jMenu1.setText("Usuário");

        jMenuItem1.setText("Cadastre-se");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem9.setText("Esqueci minha senha");
        jMenu1.add(jMenuItem9);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/P.J.png"))); // NOI18N
        jMenu5.setText("Pessoa Jurídica");

        jMenuItem11.setText("Cadastre-se");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Login");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/contact(1).png"))); // NOI18N
        jMenu2.setText("Contato");

        jMenuItem3.setText("Telefone");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("WhatsApp");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Email");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/sobreicon.png"))); // NOI18N
        jMenu4.setText("Sobre");

        jMenuItem6.setText("Atualizações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Descontos");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Novas integrações");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDeAcessoLoginPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDeAcessoLoginPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLoginPJActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Voltar pode acarretar a exclusão de seus dados. Deseja prosseguir?", "Verificação", JOptionPane.YES_NO_OPTION);
            if (resposta==JOptionPane.YES_OPTION){
                new TelaPrincipalSDI().setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_btnVoltarLoginPJActionPerformed

    private void CampSenhaLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampSenhaLoginPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampSenhaLoginPJActionPerformed

    private void campEmailLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campEmailLoginPJActionPerformed
        //        if (txtLogin_pf.isValid()){
            //            txtLogin_pf.setText(" ");
            //        }
        //        else{
            //            txtLogin_pf.setText("Digite seu login:");
            //        }
    }//GEN-LAST:event_campEmailLoginPJActionPerformed

    private void checkBoxLembrarLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLembrarLoginPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxLembrarLoginPJActionPerformed

    private void btnEntrarLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarLoginPJActionPerformed
        if (campEmailLoginPJ.getText().equals("Miguel Nicolelis") && CampSenhaLoginPJ.getText().equals("1234")){
            JOptionPane.showInputDialog("Por favor, confirme seu acesso com seu CNPJ.");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Dados não correspondentes aos usuários cadastrados.", "Acesso negado", HEIGHT);
        }
    }//GEN-LAST:event_btnEntrarLoginPJActionPerformed

    private void btnEsqueceuSenhaLoginPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqueceuSenhaLoginPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsqueceuSenhaLoginPJActionPerformed

    private void linkLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_linkLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_linkLabelAncestorAdded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPJ_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPJ_sdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPasswordField CampSenhaLoginPJ;
    javax.swing.JButton btnVoltarLoginPJ;
    javax.swing.JTextField campEmailLoginPJ;
    javax.swing.JCheckBox checkBoxLembrarLoginPJ;
    javax.swing.JPanel telaDeAcessoLoginPJ;
    // End of variables declaration//GEN-END:variables
}
