/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_interface.view;

import javax.swing.JOptionPane;
import project_interface.util.BDuserPF;

/**
 *
 * @author samueldouglasdossantos
 */
public class LoginPF_sdi extends javax.swing.JFrame {

    /**
     * Creates new form LoginPF_sdi1
     */
    public LoginPF_sdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        telaDeAcessoLginPF = new javax.swing.JPanel();
        btnVoltarLoginPF = new javax.swing.JButton();
        campSenhaLoginPF = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        campEmailLoginPF = new javax.swing.JTextField();
        checkBoxLembrarSenhaPF = new javax.swing.JCheckBox();
        javax.swing.JButton bntEntrarLoginPF = new javax.swing.JButton();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JButton btnEsqueceuSenhaLoginPF = new javax.swing.JButton();
        javax.swing.JLabel linkLabel = new javax.swing.JLabel();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem9 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu5 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem11 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem12 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem7 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        telaDeAcessoLginPF.setBackground(new java.awt.Color(19, 20, 39));
        telaDeAcessoLginPF.setToolTipText("");
        telaDeAcessoLginPF.setPreferredSize(new java.awt.Dimension(437, 672));

        btnVoltarLoginPF.setBackground(new java.awt.Color(255, 0, 0));
        btnVoltarLoginPF.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnVoltarLoginPF.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltarLoginPF.setText("Voltar");
        btnVoltarLoginPF.setMaximumSize(new java.awt.Dimension(125, 25));
        btnVoltarLoginPF.setMinimumSize(new java.awt.Dimension(125, 25));
        btnVoltarLoginPF.setPreferredSize(new java.awt.Dimension(125, 30));
        btnVoltarLoginPF.setSelected(true);
        btnVoltarLoginPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLoginPFActionPerformed(evt);
            }
        });

        campSenhaLoginPF.setText("0000000");
        campSenhaLoginPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campSenhaLoginPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campSenhaLoginPFFocusLost(evt);
            }
        });
        campSenhaLoginPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campSenhaLoginPFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Senha:");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Login:");

        campEmailLoginPF.setText("Digite seu login:");
        campEmailLoginPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campEmailLoginPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campEmailLoginPFFocusLost(evt);
            }
        });
        campEmailLoginPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campEmailLoginPFActionPerformed(evt);
            }
        });

        checkBoxLembrarSenhaPF.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        checkBoxLembrarSenhaPF.setForeground(new java.awt.Color(51, 255, 255));
        checkBoxLembrarSenhaPF.setText("Lembrar Login.");
        checkBoxLembrarSenhaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLembrarSenhaPFActionPerformed(evt);
            }
        });

        bntEntrarLoginPF.setBackground(new java.awt.Color(0, 255, 0));
        bntEntrarLoginPF.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        bntEntrarLoginPF.setForeground(new java.awt.Color(0, 0, 0));
        bntEntrarLoginPF.setText("Entrar");
        bntEntrarLoginPF.setMaximumSize(new java.awt.Dimension(75, 25));
        bntEntrarLoginPF.setMinimumSize(new java.awt.Dimension(75, 25));
        bntEntrarLoginPF.setPreferredSize(new java.awt.Dimension(125, 30));
        bntEntrarLoginPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEntrarLoginPFActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/iconestoque.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Acesso P.F");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setMinimumSize(new java.awt.Dimension(66, 25));

        btnEsqueceuSenhaLoginPF.setBackground(new java.awt.Color(0, 255, 203));
        btnEsqueceuSenhaLoginPF.setForeground(new java.awt.Color(0, 0, 0));
        btnEsqueceuSenhaLoginPF.setText("Clique aqui!");
        btnEsqueceuSenhaLoginPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueceuSenhaLoginPFActionPerformed(evt);
            }
        });

        linkLabel.setForeground(new java.awt.Color(255, 255, 255));
        linkLabel.setText("Esqueceu sua senha? ");
        linkLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                linkLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout telaDeAcessoLginPFLayout = new javax.swing.GroupLayout(telaDeAcessoLginPF);
        telaDeAcessoLginPF.setLayout(telaDeAcessoLginPFLayout);
        telaDeAcessoLginPFLayout.setHorizontalGroup(
            telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLginPFLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLginPFLayout.createSequentialGroup()
                                    .addComponent(linkLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEsqueceuSenhaLoginPF)
                                    .addGap(78, 78, 78))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLginPFLayout.createSequentialGroup()
                                    .addComponent(campEmailLoginPF, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeAcessoLginPFLayout.createSequentialGroup()
                            .addComponent(campSenhaLoginPF, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(telaDeAcessoLginPFLayout.createSequentialGroup()
                        .addGroup(telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDeAcessoLginPFLayout.createSequentialGroup()
                                .addComponent(btnVoltarLoginPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(bntEntrarLoginPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkBoxLembrarSenhaPF))
                        .addContainerGap(72, Short.MAX_VALUE))))
            .addGroup(telaDeAcessoLginPFLayout.createSequentialGroup()
                .addGroup(telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeAcessoLginPFLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaDeAcessoLginPFLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        telaDeAcessoLginPFLayout.setVerticalGroup(
            telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeAcessoLginPFLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campEmailLoginPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(campSenhaLoginPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkBoxLembrarSenhaPF)
                .addGap(57, 57, 57)
                .addGroup(telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarLoginPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntEntrarLoginPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(telaDeAcessoLginPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkLabel)
                    .addComponent(btnEsqueceuSenhaLoginPF))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDeAcessoLginPF, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDeAcessoLginPF, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/loginicon(1).png"))); // NOI18N
        jMenu1.setText("Usuário");

        jMenuItem1.setText("Cadastre-se");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem9.setText("Esqueci minha senha");
        jMenu1.add(jMenuItem9);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/P.J.png"))); // NOI18N
        jMenu5.setText("Pessoa Jurídica");

        jMenuItem11.setText("Cadastre-se");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Login");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/contact(1).png"))); // NOI18N
        jMenu2.setText("Contato");

        jMenuItem3.setText("Telefone");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("WhatsApp");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Email");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/sobreicon.png"))); // NOI18N
        jMenu4.setText("Sobre");

        jMenuItem6.setText("Atualizações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Descontos");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Novas integrações");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarLoginPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLoginPFActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Voltar pode acarretar a exclusão de seus dados. Deseja prosseguir?", "Verificação", JOptionPane.YES_NO_OPTION);
        if (resposta==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnVoltarLoginPFActionPerformed

    private void campSenhaLoginPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campSenhaLoginPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campSenhaLoginPFActionPerformed

    private void campEmailLoginPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campEmailLoginPFActionPerformed
        //        if (txtLogin_pf.isValid()){
            //            txtLogin_pf.setText(" ");
            //        }
        //        else if{
            //            txtLogin_pf.setText("Digite seu login:");
            //        }
    }//GEN-LAST:event_campEmailLoginPFActionPerformed

    private void checkBoxLembrarSenhaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLembrarSenhaPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxLembrarSenhaPFActionPerformed

    private void bntEntrarLoginPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEntrarLoginPFActionPerformed
    String email = campEmailLoginPF.getText();
    String senha = campSenhaLoginPF.getText();
    String cpf = null;

    // Validação do email
    if (!email.contains(".com") || !email.contains("@")) {
        JOptionPane.showMessageDialog(this, "Email inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;  // Retorna para evitar continuar o login com email inválido
    }

    // Primeira verificação do login (email + senha)
    if (BDuserPF.verificarLogin(email, senha, "")) {
        // Solicita o CPF para confirmação
        cpf = JOptionPane.showInputDialog("Confirme seu acesso com seu CPF:");
        if (cpf == null || cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "CPF não informado. Operação cancelada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirmação do login com CPF
        if (BDuserPF.verificarLogin(email, senha, cpf)) {
            JOptionPane.showMessageDialog(this, "Login bem-sucedido!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            new TelaMenuPF().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Credenciais inválidas! Verifique o CPF e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Credenciais inválidas! Verifique o email e senha e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bntEntrarLoginPFActionPerformed

    private void btnEsqueceuSenhaLoginPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqueceuSenhaLoginPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsqueceuSenhaLoginPFActionPerformed

    private void linkLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_linkLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_linkLabelAncestorAdded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void campEmailLoginPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campEmailLoginPFFocusGained
        if(campEmailLoginPF.getText().equals("Digite seu login:")){
            campEmailLoginPF.setText("");
        }
    }//GEN-LAST:event_campEmailLoginPFFocusGained

    private void campSenhaLoginPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campSenhaLoginPFFocusGained
        if(campSenhaLoginPF.getText().equals("0000000")){
            campSenhaLoginPF.setText("");
        }
    }//GEN-LAST:event_campSenhaLoginPFFocusGained

    private void campEmailLoginPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campEmailLoginPFFocusLost
        if(campEmailLoginPF.getText().isEmpty()){
            campEmailLoginPF.setText("Digite seu login:");
        }
    }//GEN-LAST:event_campEmailLoginPFFocusLost

    private void campSenhaLoginPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campSenhaLoginPFFocusLost
        if(campSenhaLoginPF.getText().equals("")){
            campSenhaLoginPF.setText("0000000");
        }
    }//GEN-LAST:event_campSenhaLoginPFFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPF_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPF_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPF_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPF_sdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPF_sdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnVoltarLoginPF;
    javax.swing.JTextField campEmailLoginPF;
    javax.swing.JPasswordField campSenhaLoginPF;
    javax.swing.JCheckBox checkBoxLembrarSenhaPF;
    javax.swing.JPanel telaDeAcessoLginPF;
    // End of variables declaration//GEN-END:variables
}
