/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_interface.view;

import javax.swing.JOptionPane;
import project_interface.model.Produto;
import project_interface.util.BDprodutoPJ;

/**
 *
 * @author samueldouglasdossantos
 */
public class TelaMenuPJ extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPJ
     */
    public TelaMenuPJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        TextPreço2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JButton btnEditarListaDeProduto4 = new javax.swing.JButton();
        btnDeADDProdutoNaLista2 = new javax.swing.JButton();
        javax.swing.JLabel textquantidade2 = new javax.swing.JLabel();
        javax.swing.JLabel textenomeproduto2 = new javax.swing.JLabel();
        javax.swing.JLabel texquantidade2 = new javax.swing.JLabel();
        campoTelaEstoquePreçoDoProduto2 = new javax.swing.JTextField();
        campoTelaEstoqueDeNomeDoProduto3 = new javax.swing.JTextField();
        campoTelaEstoqueQuantidadeDoProduto2 = new javax.swing.JTextField();
        javax.swing.JButton btnEditarListaDeProduto5 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDeControleDeEstoque2 = new javax.swing.JTable();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem9 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu5 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem11 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem12 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem7 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        TextPreço2.setBackground(new java.awt.Color(19, 20, 39));
        TextPreço2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Controle de Estoque:");

        btnEditarListaDeProduto4.setBackground(new java.awt.Color(0, 255, 0));
        btnEditarListaDeProduto4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnEditarListaDeProduto4.setText("Editar Lista");
        btnEditarListaDeProduto4.setMaximumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto4.setMinimumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto4.setPreferredSize(new java.awt.Dimension(125, 30));
        btnEditarListaDeProduto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarListaDeProduto4ActionPerformed(evt);
            }
        });

        btnDeADDProdutoNaLista2.setBackground(new java.awt.Color(0, 255, 0));
        btnDeADDProdutoNaLista2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnDeADDProdutoNaLista2.setText("Adicionar Produto");
        btnDeADDProdutoNaLista2.setMaximumSize(new java.awt.Dimension(125, 25));
        btnDeADDProdutoNaLista2.setMinimumSize(new java.awt.Dimension(125, 25));
        btnDeADDProdutoNaLista2.setPreferredSize(new java.awt.Dimension(125, 30));
        btnDeADDProdutoNaLista2.setSelected(true);
        btnDeADDProdutoNaLista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeADDProdutoNaLista2ActionPerformed(evt);
            }
        });

        textquantidade2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textquantidade2.setForeground(new java.awt.Color(255, 255, 255));
        textquantidade2.setText("Preço:");

        textenomeproduto2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textenomeproduto2.setForeground(new java.awt.Color(255, 255, 255));
        textenomeproduto2.setText("Nome do Produto:");

        texquantidade2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texquantidade2.setForeground(new java.awt.Color(255, 255, 255));
        texquantidade2.setText("Quantidade:");

        campoTelaEstoquePreçoDoProduto2.setText("Informe o valor do produto:");

        campoTelaEstoqueDeNomeDoProduto3.setText("Informe o nome do produto:");
        campoTelaEstoqueDeNomeDoProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelaEstoqueDeNomeDoProduto3ActionPerformed(evt);
            }
        });

        campoTelaEstoqueQuantidadeDoProduto2.setText("Informe a quantidade:");

        btnEditarListaDeProduto5.setBackground(new java.awt.Color(204, 102, 0));
        btnEditarListaDeProduto5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnEditarListaDeProduto5.setText("Excluir Produto");
        btnEditarListaDeProduto5.setMaximumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto5.setMinimumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto5.setPreferredSize(new java.awt.Dimension(125, 30));
        btnEditarListaDeProduto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarListaDeProduto5ActionPerformed(evt);
            }
        });

        tabelaDeControleDeEstoque2.setModel(new javax.swing.table.DefaultTableModel(

            // Definição do modelo da tabela
            tabelaDeControleDeEstoque2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    // Aqui você irá preencher as linhas da tabela com dados do banco de dados
                },
                new String [] {
                    "id:", "Nome:", "Preço:", "Quantidade:", "Montante:" // Cabeçalhos da tabela
                }
            ) {
                // Definindo tipos de cada coluna
                Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
                };
                // Definindo se as células são editáveis (não editáveis no caso)
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false // Não permite edição direta na tabela
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex]; // Retorna o tipo da coluna
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex]; // Impede a edição nas células
                }
            });

            // Adicionando a tabela ao JScrollPane
            jScrollPane3.setViewportView(tabelaDeControleDeEstoque2);

            // Método para carregar produtos na tabela
            private void carregarProdutosNaTabela() {
                // Limpar tabela antes de atualizar
                DefaultTableModel model = (DefaultTableModel) tabelaDeControleDeEstoque2.getModel();
                model.setRowCount(0);  // Limpa a tabela

                // Recuperar lista de produtos do banco de dados
                BDprodutoPJ bdProdutoPJ = new BDprodutoPJ();
                List<ProdutoPJ> produtos = bdProdutoPJ.listarProdutos(); // Obtém os produtos da base de dados

                // Preencher a tabela com os produtos
                for (ProdutoPJ produto : produtos) {
                    model.addRow(new Object[]{
                        produto.getId(),
                        produto.getNome(),
                        produto.getPreco(),
                        produto.getQuantidade(),
                        produto.getMontante()
                    });
                }
            }

            // Método para adicionar produto
            private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {
                String nome = campoNomeProduto.getText();
                double preco = Double.parseDouble(campoPrecoProduto.getText());
                int quantidade = Integer.parseInt(campoQuantidadeProduto.getText());

                // Verificação se os valores são válidos
                if (preco <= 0 || quantidade < 0) {
                    JOptionPane.showMessageDialog(this, "Preço e quantidade devem ser positivos.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                ProdutoPJ novoProduto = new ProdutoPJ(0, nome, preco, quantidade);
                BDprodutoPJ bdProdutoPJ = new BDprodutoPJ();

                // Chama o método de adicionar no banco
                boolean sucesso = bdProdutoPJ.adicionarProduto(novoProduto);
                if (sucesso) {
                    carregarProdutosNaTabela(); // Atualiza a tabela após adicionar o produto
                    JOptionPane.showMessageDialog(this, "Produto adicionado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao adicionar produto.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

            // Método para excluir produto
            private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {
                int linhaSelecionada = tabelaDeControleDeEstoque2.getSelectedRow();
                if (linhaSelecionada != -1) {
                    int id = (int) tabelaDeControleDeEstoque2.getValueAt(linhaSelecionada, 0);
                    BDprodutoPJ bdProdutoPJ = new BDprodutoPJ();

                    // Chama o método de exclusão do banco
                    boolean sucesso = bdProdutoPJ.excluirProduto(id);
                    if (sucesso) {
                        carregarProdutosNaTabela(); // Atualiza a tabela após excluir o produto
                        JOptionPane.showMessageDialog(this, "Produto excluído com sucesso.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir produto.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            // Método para remover quantidade de um produto
            private void btnRemoverQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {
                int linhaSelecionada = tabelaDeControleDeEstoque2.getSelectedRow();
                if (linhaSelecionada != -1) {
                    int id = (int) tabelaDeControleDeEstoque2.getValueAt(linhaSelecionada, 0);
                    int quantidadeRemover = Integer.parseInt(JOptionPane.showInputDialog(this, "Quantidade a remover:"));

                    // Verificação de quantidade a ser removida
                    if (quantidadeRemover <= 0) {
                        JOptionPane.showMessageDialog(this, "Quantidade a remover deve ser positiva.", "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    BDprodutoPJ bdProdutoPJ = new BDprodutoPJ();

                    // Chama o método de remover quantidade do banco
                    boolean sucesso = bdProdutoPJ.removerQuantidadeProduto(id, quantidadeRemover);
                    if (sucesso) {
                        carregarProdutosNaTabela(); // Atualiza a tabela após a remoção de quantidade
                        JOptionPane.showMessageDialog(this, "Quantidade removida com sucesso.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao remover quantidade.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            // Método para modificar produto (preço ou quantidade)
            private void btnModificarProdutoActionPerformed(java.awt.event.ActionEvent evt) {
                int linhaSelecionada = tabelaDeControleDeEstoque2.getSelectedRow();
                if (linhaSelecionada != -1) {
                    int id = (int) tabelaDeControleDeEstoque2.getValueAt(linhaSelecionada, 0);
                    String nome = campoNomeProduto.getText();
                    double preco = Double.parseDouble(campoPrecoProduto.getText());
                    int quantidade = Integer.parseInt(campoQuantidadeProduto.getText());

                    ProdutoPJ produtoModificado = new ProdutoPJ(id, nome, preco, quantidade);
                    BDprodutoPJ bdProdutoPJ = new BDprodutoPJ();

                    // Chama o método de modificação do banco
                    boolean sucesso = bdProdutoPJ.modificarProduto(id, produtoModificado);
                    if (sucesso) {
                        carregarProdutosNaTabela(); // Atualiza a tabela após modificar o produto
                        JOptionPane.showMessageDialog(this, "Produto modificado com sucesso.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao modificar produto.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        );
        jScrollPane3.setViewportView(tabelaDeControleDeEstoque2);

        javax.swing.GroupLayout TextPreço2Layout = new javax.swing.GroupLayout(TextPreço2);
        TextPreço2.setLayout(TextPreço2Layout);
        TextPreço2Layout.setHorizontalGroup(
            TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPreço2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textenomeproduto2)
                    .addComponent(btnDeADDProdutoNaLista2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(btnEditarListaDeProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarListaDeProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreço2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoTelaEstoquePreçoDoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoqueQuantidadeDoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoqueDeNomeDoProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
            .addGroup(TextPreço2Layout.createSequentialGroup()
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPreço2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TextPreço2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        TextPreço2Layout.setVerticalGroup(
            TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPreço2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelaEstoqueDeNomeDoProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textenomeproduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoquePreçoDoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoqueQuantidadeDoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TextPreço2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeADDProdutoNaLista2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarListaDeProduto4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEditarListaDeProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextPreço2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TextPreço2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/loginicon(1).png"))); // NOI18N
        jMenu1.setText("Usuário");

        jMenuItem1.setText("Cadastre-se");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem9.setText("Esqueci minha senha");
        jMenu1.add(jMenuItem9);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/P.J.png"))); // NOI18N
        jMenu5.setText("Pessoa Jurídica");

        jMenuItem11.setText("Cadastre-se");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Login");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/contact(1).png"))); // NOI18N
        jMenu2.setText("Contato");

        jMenuItem3.setText("Telefone");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("WhatsApp");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Email");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_interface/images/sobreicon.png"))); // NOI18N
        jMenu4.setText("Sobre");

        jMenuItem6.setText("Atualizações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Descontos");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Novas integrações");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarListaDeProduto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarListaDeProduto4ActionPerformed

    }//GEN-LAST:event_btnEditarListaDeProduto4ActionPerformed

    private void btnDeADDProdutoNaLista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeADDProdutoNaLista2ActionPerformed
        try {
                String nome = campoTelaEstoqueDeNomeDoProduto3.getText();
                double preco = Double.parseDouble(campoTelaEstoquePreçoDoProduto2.getText());
                int quantidade = Integer.parseInt(campoTelaEstoqueQuantidadeDoProduto2.getText());

                Produto produto = new Produto(nome, preco, quantidade);
                produtoDAO.inserirProduto(produto);

                JOptionPane.showMessageDialog(frame, "Produto adicionado com sucesso!");
                atualizarTabela(tabela);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(frame, "Por favor, insira valores válidos.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnDeADDProdutoNaLista2ActionPerformed

    private void campoTelaEstoqueDeNomeDoProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelaEstoqueDeNomeDoProduto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelaEstoqueDeNomeDoProduto3ActionPerformed

    private void btnEditarListaDeProduto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarListaDeProduto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarListaDeProduto5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel TextPreço2;
    javax.swing.JButton btnDeADDProdutoNaLista2;
    javax.swing.JTextField campoTelaEstoqueDeNomeDoProduto3;
    javax.swing.JTextField campoTelaEstoquePreçoDoProduto2;
    javax.swing.JTextField campoTelaEstoqueQuantidadeDoProduto2;
    javax.swing.JTable tabelaDeControleDeEstoque2;
    // End of variables declaration//GEN-END:variables
}
