/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javanassaut;

/**
 *
 * @author aland
 */
public class TelaDeMenuPJ extends javax.swing.JDialog {

    /**
     * Creates new form TelaDeMenuPJ
     */
    public TelaDeMenuPJ(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        TextPreço = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEditarListaDeProduto = new javax.swing.JButton();
        btnDeADDProdutoNaLista = new javax.swing.JButton();
        textquantidade = new javax.swing.JLabel();
        textenomeproduto = new javax.swing.JLabel();
        texquantidade = new javax.swing.JLabel();
        campoTelaEstoquePreçoDoProduto = new javax.swing.JTextField();
        campoTelaEstoqueDeNomeDoProduto1 = new javax.swing.JTextField();
        campoTelaEstoqueQuantidadeDoProduto = new javax.swing.JTextField();
        btnEditarListaDeProduto1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeControleDeEstoque = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPerfilTelaPrincipalPJ = new javax.swing.JMenu();
        menubtnDeSairDaTelaPrincipalPj = new javax.swing.JMenuItem();
        MenuDeDuvidasFrequentesPJ = new javax.swing.JMenu();
        MenuDeSobraPJ = new javax.swing.JMenu();
        MenubtnAtualizacaoPJ = new javax.swing.JMenuItem();
        MenubtnDescontoPJ = new javax.swing.JMenuItem();
        MenubtnNovasIntegracaoPJ = new javax.swing.JMenuItem();
        MenuContatoPJ = new javax.swing.JMenu();
        MenubtnTelefonePJ = new javax.swing.JMenuItem();
        MenubtnWhatsAppPJ = new javax.swing.JMenuItem();
        MenubtnEmailPJ = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TELA PRINCIPAL DO PJ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(19, 20, 39));

        TextPreço.setBackground(new java.awt.Color(19, 20, 39));
        TextPreço.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Controle de Estoque:");

        btnEditarListaDeProduto.setBackground(new java.awt.Color(0, 255, 0));
        btnEditarListaDeProduto.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnEditarListaDeProduto.setText("Editar Lista");
        btnEditarListaDeProduto.setMaximumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto.setMinimumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto.setPreferredSize(new java.awt.Dimension(125, 30));
        btnEditarListaDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarListaDeProdutoActionPerformed(evt);
            }
        });

        btnDeADDProdutoNaLista.setBackground(new java.awt.Color(0, 255, 0));
        btnDeADDProdutoNaLista.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnDeADDProdutoNaLista.setText("Adicionar Produto");
        btnDeADDProdutoNaLista.setMaximumSize(new java.awt.Dimension(125, 25));
        btnDeADDProdutoNaLista.setMinimumSize(new java.awt.Dimension(125, 25));
        btnDeADDProdutoNaLista.setPreferredSize(new java.awt.Dimension(125, 30));
        btnDeADDProdutoNaLista.setSelected(true);
        btnDeADDProdutoNaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeADDProdutoNaListaActionPerformed(evt);
            }
        });

        textquantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textquantidade.setForeground(new java.awt.Color(255, 255, 255));
        textquantidade.setText("Preço:");

        textenomeproduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textenomeproduto.setForeground(new java.awt.Color(255, 255, 255));
        textenomeproduto.setText("Nome do Produto:");

        texquantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texquantidade.setForeground(new java.awt.Color(255, 255, 255));
        texquantidade.setText("Quantidade:");

        campoTelaEstoquePreçoDoProduto.setText("Informe o valor do produto.");

        campoTelaEstoqueDeNomeDoProduto1.setText("Informe o nome do produto.");
        campoTelaEstoqueDeNomeDoProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelaEstoqueDeNomeDoProduto1ActionPerformed(evt);
            }
        });

        campoTelaEstoqueQuantidadeDoProduto.setText("Informe a quantidade.");

        btnEditarListaDeProduto1.setBackground(new java.awt.Color(204, 102, 0));
        btnEditarListaDeProduto1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnEditarListaDeProduto1.setText("Excluir Produto");
        btnEditarListaDeProduto1.setMaximumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto1.setMinimumSize(new java.awt.Dimension(75, 25));
        btnEditarListaDeProduto1.setPreferredSize(new java.awt.Dimension(125, 30));
        btnEditarListaDeProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarListaDeProduto1ActionPerformed(evt);
            }
        });

        tabelaDeControleDeEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Quantidade", "Montante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDeControleDeEstoque);

        javax.swing.GroupLayout TextPreçoLayout = new javax.swing.GroupLayout(TextPreço);
        TextPreço.setLayout(TextPreçoLayout);
        TextPreçoLayout.setHorizontalGroup(
            TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPreçoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textenomeproduto)
                    .addComponent(btnDeADDProdutoNaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(btnEditarListaDeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnEditarListaDeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreçoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoTelaEstoquePreçoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoqueQuantidadeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoqueDeNomeDoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
            .addGroup(TextPreçoLayout.createSequentialGroup()
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPreçoLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TextPreçoLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextPreçoLayout.setVerticalGroup(
            TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPreçoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelaEstoqueDeNomeDoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textenomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoquePreçoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaEstoqueQuantidadeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeADDProdutoNaLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarListaDeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarListaDeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextPreço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TextPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPerfilTelaPrincipalPJ.setText("Pessoa Jurídica");

        menubtnDeSairDaTelaPrincipalPj.setText("Sair");
        MenuPerfilTelaPrincipalPJ.add(menubtnDeSairDaTelaPrincipalPj);

        jMenuBar1.add(MenuPerfilTelaPrincipalPJ);

        MenuDeDuvidasFrequentesPJ.setText("Dúvidas frequentes");
        jMenuBar1.add(MenuDeDuvidasFrequentesPJ);

        MenuDeSobraPJ.setText("Sobre");

        MenubtnAtualizacaoPJ.setText("Atualizações");
        MenubtnAtualizacaoPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenubtnAtualizacaoPJActionPerformed(evt);
            }
        });
        MenuDeSobraPJ.add(MenubtnAtualizacaoPJ);

        MenubtnDescontoPJ.setText("Descontos");
        MenuDeSobraPJ.add(MenubtnDescontoPJ);

        MenubtnNovasIntegracaoPJ.setText("Novas integrações");
        MenuDeSobraPJ.add(MenubtnNovasIntegracaoPJ);

        jMenuBar1.add(MenuDeSobraPJ);

        MenuContatoPJ.setText("Contato");

        MenubtnTelefonePJ.setText("Telefone");
        MenuContatoPJ.add(MenubtnTelefonePJ);

        MenubtnWhatsAppPJ.setText("WhatsApp");
        MenuContatoPJ.add(MenubtnWhatsAppPJ);

        MenubtnEmailPJ.setText("Email");
        MenubtnEmailPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenubtnEmailPJActionPerformed(evt);
            }
        });
        MenuContatoPJ.add(MenubtnEmailPJ);

        jMenuBar1.add(MenuContatoPJ);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenubtnAtualizacaoPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenubtnAtualizacaoPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenubtnAtualizacaoPJActionPerformed

    private void btnEditarListaDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarListaDeProdutoActionPerformed

    }//GEN-LAST:event_btnEditarListaDeProdutoActionPerformed

    private void btnDeADDProdutoNaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeADDProdutoNaListaActionPerformed

    }//GEN-LAST:event_btnDeADDProdutoNaListaActionPerformed

    private void campoTelaEstoqueDeNomeDoProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelaEstoqueDeNomeDoProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelaEstoqueDeNomeDoProduto1ActionPerformed

    private void btnEditarListaDeProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarListaDeProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarListaDeProduto1ActionPerformed

    private void MenubtnEmailPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenubtnEmailPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenubtnEmailPJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDeMenuPJ dialog = new TelaDeMenuPJ(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuContatoPJ;
    private javax.swing.JMenu MenuDeDuvidasFrequentesPJ;
    private javax.swing.JMenu MenuDeSobraPJ;
    private javax.swing.JMenu MenuPerfilTelaPrincipalPJ;
    private javax.swing.JMenuItem MenubtnAtualizacaoPJ;
    private javax.swing.JMenuItem MenubtnDescontoPJ;
    private javax.swing.JMenuItem MenubtnEmailPJ;
    private javax.swing.JMenuItem MenubtnNovasIntegracaoPJ;
    private javax.swing.JMenuItem MenubtnTelefonePJ;
    private javax.swing.JMenuItem MenubtnWhatsAppPJ;
    private javax.swing.JPanel TextPreço;
    javax.swing.JButton btnDeADDProdutoNaLista;
    private javax.swing.JButton btnEditarListaDeProduto;
    private javax.swing.JButton btnEditarListaDeProduto1;
    private javax.swing.JTextField campoTelaEstoqueDeNomeDoProduto1;
    private javax.swing.JTextField campoTelaEstoquePreçoDoProduto;
    private javax.swing.JTextField campoTelaEstoqueQuantidadeDoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JMenuItem menubtnDeSairDaTelaPrincipalPj;
    private javax.swing.JTable tabelaDeControleDeEstoque;
    private javax.swing.JLabel texquantidade;
    private javax.swing.JLabel textenomeproduto;
    private javax.swing.JLabel textquantidade;
    // End of variables declaration//GEN-END:variables
}
