/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javanassaut;

/**
 *
 * @author aland
 */
public class TelaDeMenuPF extends javax.swing.JDialog {

    /**
     * Creates new form TelaDeMenuPF
     */
    public TelaDeMenuPF(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextPreço = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnComprarProdutoDaListaPF = new javax.swing.JButton();
        btnDeADDProdutoNaListaPF = new javax.swing.JButton();
        textenomeproduto = new javax.swing.JLabel();
        texquantidade = new javax.swing.JLabel();
        campoTelaProdutoVendaDeNomeDoProdutoPF = new javax.swing.JTextField();
        campoTelaVendaProdutoQuantidadeDoProdutoPF = new javax.swing.JTextField();
        btnAPagarProdutoDaListaPF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TelaDeVendatabelaDeComprarDaPessoaFisica = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDeProdutosNoEstoqueParaVendaPF = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPessoaFisica = new javax.swing.JMenu();
        btnSairDaTelaPrincipalPF = new javax.swing.JMenuItem();
        menuDeDuvidasFrequentesPF = new javax.swing.JMenu();
        MenuSobreTelaPrincipalPF = new javax.swing.JMenu();
        MenubtnAtualizaçãoTelaPrincipalPF = new javax.swing.JMenuItem();
        MenubtnDescontosTelaPrincipalPF = new javax.swing.JMenuItem();
        MenubtnNovasIntegracaoSobreTelaPrincipalPF = new javax.swing.JMenuItem();
        MenuContadoTelaPrincipalPF = new javax.swing.JMenu();
        MenubtnTelefoneTelaPrincipalPF = new javax.swing.JMenuItem();
        MenubtnWhatsAppTelaPrincipalPF = new javax.swing.JMenuItem();
        MenubtnEmailTelaPrincipalPF = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TELA PRINCIPAL DE PF");

        TextPreço.setBackground(new java.awt.Color(19, 20, 39));
        TextPreço.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sua Lista:");

        btnComprarProdutoDaListaPF.setBackground(new java.awt.Color(0, 255, 0));
        btnComprarProdutoDaListaPF.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnComprarProdutoDaListaPF.setText("Comprar");
        btnComprarProdutoDaListaPF.setMaximumSize(new java.awt.Dimension(75, 25));
        btnComprarProdutoDaListaPF.setMinimumSize(new java.awt.Dimension(75, 25));
        btnComprarProdutoDaListaPF.setPreferredSize(new java.awt.Dimension(125, 30));
        btnComprarProdutoDaListaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarProdutoDaListaPFActionPerformed(evt);
            }
        });

        btnDeADDProdutoNaListaPF.setBackground(new java.awt.Color(0, 255, 0));
        btnDeADDProdutoNaListaPF.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnDeADDProdutoNaListaPF.setText("Adicionor Produto ");
        btnDeADDProdutoNaListaPF.setMaximumSize(new java.awt.Dimension(125, 25));
        btnDeADDProdutoNaListaPF.setMinimumSize(new java.awt.Dimension(125, 25));
        btnDeADDProdutoNaListaPF.setPreferredSize(new java.awt.Dimension(125, 30));
        btnDeADDProdutoNaListaPF.setSelected(true);
        btnDeADDProdutoNaListaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeADDProdutoNaListaPFActionPerformed(evt);
            }
        });

        textenomeproduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textenomeproduto.setForeground(new java.awt.Color(255, 255, 255));
        textenomeproduto.setText("Nome do Produto:");

        texquantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texquantidade.setForeground(new java.awt.Color(255, 255, 255));
        texquantidade.setText("Quantidade:");

        campoTelaProdutoVendaDeNomeDoProdutoPF.setText("Informe o nome do produto.");
        campoTelaProdutoVendaDeNomeDoProdutoPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelaProdutoVendaDeNomeDoProdutoPFActionPerformed(evt);
            }
        });

        campoTelaVendaProdutoQuantidadeDoProdutoPF.setText("Informe a quantidade.");

        btnAPagarProdutoDaListaPF.setBackground(new java.awt.Color(204, 102, 0));
        btnAPagarProdutoDaListaPF.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnAPagarProdutoDaListaPF.setText("Apagar produto");
        btnAPagarProdutoDaListaPF.setMaximumSize(new java.awt.Dimension(75, 25));
        btnAPagarProdutoDaListaPF.setMinimumSize(new java.awt.Dimension(75, 25));
        btnAPagarProdutoDaListaPF.setPreferredSize(new java.awt.Dimension(125, 30));
        btnAPagarProdutoDaListaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPagarProdutoDaListaPFActionPerformed(evt);
            }
        });

        TelaDeVendatabelaDeComprarDaPessoaFisica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TelaDeVendatabelaDeComprarDaPessoaFisica);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produtos a venda:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Produtos a venda:");

        tabelaDeProdutosNoEstoqueParaVendaPF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaDeProdutosNoEstoqueParaVendaPF);

        javax.swing.GroupLayout TextPreçoLayout = new javax.swing.GroupLayout(TextPreço);
        TextPreço.setLayout(TextPreçoLayout);
        TextPreçoLayout.setHorizontalGroup(
            TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreçoLayout.createSequentialGroup()
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPreçoLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textenomeproduto)
                            .addComponent(texquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreçoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeADDProdutoNaListaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)))
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPreçoLayout.createSequentialGroup()
                        .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTelaProdutoVendaDeNomeDoProdutoPF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTelaVendaProdutoQuantidadeDoProdutoPF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TextPreçoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnComprarProdutoDaListaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TextPreçoLayout.createSequentialGroup()
                                .addComponent(btnAPagarProdutoDaListaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreçoLayout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPreçoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(TextPreçoLayout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextPreçoLayout.setVerticalGroup(
            TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPreçoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textenomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaProdutoVendaDeNomeDoProdutoPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelaVendaProdutoQuantidadeDoProdutoPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprarProdutoDaListaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeADDProdutoNaListaPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAPagarProdutoDaListaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TextPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuPessoaFisica.setText("Pessoa Física");

        btnSairDaTelaPrincipalPF.setText("Sair");
        btnSairDaTelaPrincipalPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairDaTelaPrincipalPFActionPerformed(evt);
            }
        });
        menuPessoaFisica.add(btnSairDaTelaPrincipalPF);

        jMenuBar1.add(menuPessoaFisica);

        menuDeDuvidasFrequentesPF.setText("Dúvidas frequentes");
        jMenuBar1.add(menuDeDuvidasFrequentesPF);

        MenuSobreTelaPrincipalPF.setText("Sobre");

        MenubtnAtualizaçãoTelaPrincipalPF.setText("Atualizações");
        MenubtnAtualizaçãoTelaPrincipalPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenubtnAtualizaçãoTelaPrincipalPFActionPerformed(evt);
            }
        });
        MenuSobreTelaPrincipalPF.add(MenubtnAtualizaçãoTelaPrincipalPF);

        MenubtnDescontosTelaPrincipalPF.setText("Descontos");
        MenuSobreTelaPrincipalPF.add(MenubtnDescontosTelaPrincipalPF);

        MenubtnNovasIntegracaoSobreTelaPrincipalPF.setText("Novas integrações");
        MenuSobreTelaPrincipalPF.add(MenubtnNovasIntegracaoSobreTelaPrincipalPF);

        jMenuBar1.add(MenuSobreTelaPrincipalPF);

        MenuContadoTelaPrincipalPF.setText("Contato");

        MenubtnTelefoneTelaPrincipalPF.setText("Telefone");
        MenuContadoTelaPrincipalPF.add(MenubtnTelefoneTelaPrincipalPF);

        MenubtnWhatsAppTelaPrincipalPF.setText("WhatsApp");
        MenuContadoTelaPrincipalPF.add(MenubtnWhatsAppTelaPrincipalPF);

        MenubtnEmailTelaPrincipalPF.setText("Email");
        MenuContadoTelaPrincipalPF.add(MenubtnEmailTelaPrincipalPF);

        jMenuBar1.add(MenuContadoTelaPrincipalPF);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextPreço, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextPreço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairDaTelaPrincipalPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairDaTelaPrincipalPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairDaTelaPrincipalPFActionPerformed

    private void MenubtnAtualizaçãoTelaPrincipalPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenubtnAtualizaçãoTelaPrincipalPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenubtnAtualizaçãoTelaPrincipalPFActionPerformed

    private void btnComprarProdutoDaListaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarProdutoDaListaPFActionPerformed

    }//GEN-LAST:event_btnComprarProdutoDaListaPFActionPerformed

    private void btnDeADDProdutoNaListaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeADDProdutoNaListaPFActionPerformed

    }//GEN-LAST:event_btnDeADDProdutoNaListaPFActionPerformed

    private void campoTelaProdutoVendaDeNomeDoProdutoPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelaProdutoVendaDeNomeDoProdutoPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelaProdutoVendaDeNomeDoProdutoPFActionPerformed

    private void btnAPagarProdutoDaListaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPagarProdutoDaListaPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAPagarProdutoDaListaPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDeMenuPF dialog = new TelaDeMenuPF(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuContadoTelaPrincipalPF;
    private javax.swing.JMenu MenuSobreTelaPrincipalPF;
    private javax.swing.JMenuItem MenubtnAtualizaçãoTelaPrincipalPF;
    private javax.swing.JMenuItem MenubtnDescontosTelaPrincipalPF;
    private javax.swing.JMenuItem MenubtnEmailTelaPrincipalPF;
    private javax.swing.JMenuItem MenubtnNovasIntegracaoSobreTelaPrincipalPF;
    private javax.swing.JMenuItem MenubtnTelefoneTelaPrincipalPF;
    private javax.swing.JMenuItem MenubtnWhatsAppTelaPrincipalPF;
    private javax.swing.JTable TelaDeVendatabelaDeComprarDaPessoaFisica;
    private javax.swing.JPanel TextPreço;
    private javax.swing.JButton btnAPagarProdutoDaListaPF;
    private javax.swing.JButton btnComprarProdutoDaListaPF;
    javax.swing.JButton btnDeADDProdutoNaListaPF;
    private javax.swing.JMenuItem btnSairDaTelaPrincipalPF;
    private javax.swing.JTextField campoTelaProdutoVendaDeNomeDoProdutoPF;
    private javax.swing.JTextField campoTelaVendaProdutoQuantidadeDoProdutoPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuDeDuvidasFrequentesPF;
    private javax.swing.JMenu menuPessoaFisica;
    private javax.swing.JTable tabelaDeProdutosNoEstoqueParaVendaPF;
    private javax.swing.JLabel texquantidade;
    private javax.swing.JLabel textenomeproduto;
    // End of variables declaration//GEN-END:variables
}
